export {
  generateWavePath,
  getWaveY,
  getWaveLength,
  type WaveOptions,
  DEFAULT_COLORED_WAVE,
  COLORED_STRAND_2,
  COLORED_STRAND_3,
  COLORED_STRAND_4,
  GRAY_STRAND_1,
  GRAY_STRAND_2,
  GRAY_STRAND_3,
  GRAY_STRAND_4,
  GRAY_STRAND_5,
} from './v2/thread/wavePath';
