/**
 * Locked Chart copy. Deterministic by design: labels and product language are
 * never generated. Principle: never hype, always orient.
 */
export const CHART_COPY = {
  title: 'Chart',
  labels: {
    reinforcing: 'REINFORCING',
    currentWaypoint: 'CURRENT WAYPOINT',
    oneMove: 'ONE MOVE',
    yourDestination: 'YOUR DESTINATION',
    courseLog: 'COURSE LOG',
    suggestedMoves: 'SUGGESTED MOVES',
    yourMoves: 'YOUR MOVES',
    onYourChart: 'ON YOUR CHART',
    yourChart: 'YOUR CHART',
    waypointReached: 'WAYPOINT REACHED',
    next: 'NEXT',
    destinationReached: 'DESTINATION REACHED',
    here: 'HERE',
    there: 'THERE',
    alreadySeen: 'YOU’VE ALREADY SEEN IT.',
  },
  empty: {
    headline: 'Give this Anchor somewhere to go.',
    support: 'A destination, broken into real waypoints you can actually reach.',
    cta: 'Create a Chart',
  },
  creation: {
    headerTitle: 'Create Chart',
    visionHeadline: 'Now let’s map the way there.',
    visionSupport: 'Your Vision shows where this Anchor is going.',
    startQuestion: 'Where are you starting from?',
    startSupportWithVision: 'We know where you’re going. Give us enough context to map the first stretch.',
    startSupportWithoutVision: 'Tell us where things stand today, and what would make this feel real.',
    startPlaceholder: 'Where things stand today…',
    continue: 'Continue',
    viewVision: 'View Vision',
  },
  generation: {
    headerTitle: 'Creating your Chart',
    headline: 'Mapping the space between.',
    support: 'Finding the meaningful changes between where you are and your destination.',
    phrases: ['Analyzing your intention', 'Finding meaningful milestones', 'Shaping your route', 'Mapping the space between'],
    longWait: ['Still mapping the best route.', 'Complex destinations can take another moment.'],
  },
  followUp: {
    headline: 'One more thing.',
    support: 'A little more context makes the route fit.',
    placeholder: 'Your answer…',
  },
  review: {
    headerTitle: 'Your first route',
    headline: 'Here’s a route to start with.',
    outline: 'We couldn’t map this one automatically. Here’s a simple outline — rename each waypoint so it fits.',
    evolve: 'This route is a starting point. You can change it as the path becomes clearer.',
    addWaypoint: 'Add waypoint',
    adjust: 'Adjust route',
    confirm: 'Looks right',
    oneMoveHint: 'Your first move',
  },
  revealed: {
    headerTitle: 'Your Chart',
    headline: 'Your route is ready.',
    support: 'A clearer path from here to there.',
    cta: 'Explore your Chart',
  },
  adjust: {
    headerTitle: 'Adjust Route',
    headline: 'What needs to change?',
    support: 'Tell us what isn’t working and we’ll suggest a new route.',
    detailPlaceholder: 'Tell us more…',
    cta: 'Update my route',
    keep: 'Keep route',
    stillRight: 'Still the right route?',
    adjustAhead: 'Adjust what’s ahead',
    protected: 'Waypoints you’ve reached stay as they are.',
    rewriteTitle: 'Rewrite part of your route?',
    rewriteBody: 'This removes a waypoint you’ve already worked on. Your completed moves stay in your history.',
    rewriteConfirm: 'Rewrite it',
    review: 'Here’s the revised route.',
    reviewSupport: 'Keep what fits. Change what doesn’t.',
    apply: 'Use this route',
  },
  reasons: [
    { key: 'TOO_MANY_STEPS', label: 'Too many steps' },
    { key: 'TOO_FEW_STEPS', label: 'Too few steps' },
    { key: 'DIFFERENT_MILESTONES', label: 'Different milestones' },
    { key: 'FURTHER_ALONG', label: 'I’m further along' },
    { key: 'CHANGE_DESTINATION', label: 'Change the destination' },
    { key: 'OTHER', label: 'Other' },
  ] as const,
  active: {
    markComplete: 'Mark complete',
    viewVision: 'View Vision',
    addMove: 'Add a move',
    noMove: 'What’s one thing you can do next?',
    noMoveCta: 'Choose a move',
    openChart: 'Open Chart',
    viewChart: 'View Chart',
    courseLogCta: 'View course log',
    offline: 'Showing your saved Chart. Changes need a connection.',
  },
  waypoint: {
    headerTitle: 'Waypoint',
    markComplete: 'Mark waypoint complete',
    confirmTitle: 'Mark this waypoint reached?',
    confirmBody: 'Your route moves forward to the next waypoint.',
    confirmCta: 'Yes, I’m here',
    notYet: 'Not yet',
    suggest: 'Suggest moves',
    suggestUnavailable: 'Suggestions aren’t available right now. Add your own move.',
    addMove: 'Add a move',
    progress: 'Update progress',
    edit: 'Edit',
    remove: 'Remove waypoint',
  },
  reached: {
    destinationHeadline: 'Destination reached.',
    destinationSupport: 'What you once pictured is now part of your history.',
    viewJourney: 'View your journey',
    release: 'Release Anchor',
  },
  errors: {
    offline: 'You’re offline. Chart needs a connection for this.',
    load: 'We couldn’t open this Chart.',
    loadSupport: 'Check your connection and try again.',
    disabled: 'Chart isn’t available yet.',
    disabledSupport: 'It will appear here as soon as it is.',
    retry: 'Try again',
    generation: 'We couldn’t finish mapping this route.',
    generationSupport: 'You can try again, or start with a simple outline you shape yourself.',
    manual: 'Start with an outline',
    save: 'Your route wasn’t saved.',
    saveSupport: 'Nothing was lost — try again when you’re connected.',
    adjust: 'We couldn’t revise the route right now. Your route is unchanged.',
    released: 'This Anchor has been released.',
    releasedSupport: 'Its Chart is preserved in your journey history.',
    missingAnchor: 'This Anchor is no longer available.',
    action: 'That didn’t go through. Try again.',
    rateLimited: 'Too many route requests just now. Try again in a little while.',
  },
} as const;

/** The category shapes the question's lens; the user's own words drive the plan. */
export const CHART_CATEGORY_PROMPT: Record<string, string> = {
  career: 'What would mark real progress toward this outcome?',
  health: 'What changes would show you this is becoming real?',
  creativity: 'What needs to exist before this feels complete?',
  relationships: 'What would you notice changing between you?',
  abundance: 'What would show you this is becoming real?',
  learning: 'What would you be able to do that you can’t yet?',
  family: 'What would home feel like once this is true?',
  spirituality: 'How would this show up in an ordinary day?',
  adventure: 'What needs to be in place before you go?',
  focus: 'What would protected, finished work look like?',
  desire: 'What would make this recognizably real?',
  custom: 'What would make you say you’ve made real progress?',
};

export function chartCategoryPrompt(category?: string | null): string {
  return CHART_CATEGORY_PROMPT[category?.trim().toLowerCase() ?? ''] ?? CHART_CATEGORY_PROMPT.custom;
}

export function reviewSupportCopy(count: number): string {
  return `We found ${count} meaningful waypoint${count === 1 ? '' : 's'} for this destination. Keep what fits. Change what doesn’t.`;
}
