import React, { useState } from 'react';
import { Text, View, StyleSheet } from 'react-native';
import { ArrowLeft, Plus, UserRound } from 'lucide-react-native';
import { useNavigation } from '@react-navigation/native';
import { CircularAnchorRenderer, V2ActivityIndicator, V2Badge, V2Button, V2ContentStack, V2Divider, V2EmptyState, V2IconButton, V2InlineError, V2ListRow, V2Screen, V2Section, V2SectionHeader, V2SegmentedControl, V2Skeleton, V2Surface, V2ThreadStrength, V2TopBar } from '@/components/v2';
import { V2_SAMPLE_ANCHOR_SVGS } from '@/constants/v2';
import { categories, colors, practiceColors, spacing, typography } from '@/theme/v2';

const swatches = Object.entries(categories);
const practiceSwatches = Object.entries(practiceColors);
export function V2SystemGallery() {
  const navigation = useNavigation<any>();
  const [segment, setSegment] = useState('week');
  const [loading, setLoading] = useState(false);
  return <V2Screen scroll testID="v2-system-gallery">
    <V2TopBar title="System gallery" onBackPress={() => navigation.goBack()} utility={<V2IconButton icon={<UserRound size={20} color={colors.text.primary} />} accessibilityLabel="Profile" surface />} />
    <Text style={styles.intro}>A development-only visual QA laboratory. These primitives are the approved V2 building blocks.</Text>
    <V2Section><V2SectionHeader title="Color" supportingCopy="Warm neutrals, centralized category and Practice semantics." /><V2Surface><Text style={styles.label}>Base neutrals</Text><View style={styles.swatches}>{[['Canvas', colors.canvas], ['Surface', colors.surface], ['Grouped', colors.grouped], ['Border', colors.border.default], ['Primary', colors.text.primary], ['Secondary', colors.text.secondary]].map(([name, color]) => <Swatch key={name} name={name} color={color} />)}</View><Text style={styles.label}>Categories</Text><View style={styles.swatches}>{swatches.map(([name, color]) => <Swatch key={name} name={name} color={color} />)}</View><Text style={styles.label}>Practice</Text><View style={styles.swatches}>{practiceSwatches.map(([name, color]) => <Swatch key={name} name={name} color={color} />)}</View></V2Surface></V2Section>
    <V2Section><V2SectionHeader title="Typography" /><V2Surface><Text style={styles.display}>Clarity has a pulse.</Text><Text style={styles.heading}>Major heading</Text><Text style={styles.body}>Figtree carries the functional interface with comfortable reading rhythm and durable hierarchy.</Text><Text style={styles.caption}>CAPTION / UTILITY / 12PX</Text><Text style={styles.numeric}>68</Text></V2Surface></V2Section>
    <V2Section><V2SectionHeader title="Actions" /><V2ContentStack><V2Button size="large" accessibilityLabel="Continue">Continue</V2Button><V2Button variant="secondary" iconLeft={<Plus size={18} color={colors.text.primary} />} accessibilityLabel="Add anchor">Add Anchor</V2Button><V2Button variant="tertiary" accessibilityLabel="Tertiary action">Quiet action</V2Button><V2Button variant="destructive" accessibilityLabel="Delete Anchor">Delete Anchor</V2Button><V2Button disabled accessibilityLabel="Disabled action">Disabled</V2Button><V2Button loading={loading} onPress={() => setLoading((state) => !state)} accessibilityLabel="Toggle button loading">Toggle loading</V2Button><View style={styles.iconRow}><V2IconButton icon={<ArrowLeft size={22} color={colors.text.primary} />} accessibilityLabel="Go back" surface /><V2IconButton icon={<Plus size={22} color={colors.text.primary} />} accessibilityLabel="Add Anchor" surface /></View></V2ContentStack></V2Section>
    <V2Section><V2SectionHeader title="Labels and selection" /><V2Surface><View style={styles.badges}><V2Badge label="Career" tone="category" /><V2Badge label="Focus" tone="practice" /><V2Badge label="Pro" tone="neutral" /><V2Badge label="Complete" tone="success" /></View><V2SegmentedControl accessibilityLabel="Time range" value={segment} onChange={setSegment} options={[{ value: 'week', label: 'Week' }, { value: 'month', label: 'Month' }, { value: 'all', label: 'All' }]} /></V2Surface></V2Section>
    <V2Section><V2SectionHeader title="Rows and surfaces" actionLabel="See all" /><V2Surface><V2ListRow icon={<Plus size={18} color={colors.semantic.info} />} title="Focus Practice" subtitle="12 minutes · ready when you are" accent={practiceColors.focus} onPress={() => undefined} disclosure /><V2Divider /><V2ListRow title="A canvas-level row" subtitle="Rows do not require a card." trailing={<Text style={styles.rowTrailing}>Today</Text>} /></V2Surface></V2Section>
    <V2Section><V2SectionHeader title="Circular Anchor" supportingCopy="Flat category field, reused vector renderer, no aura stack." /><V2Surface><View style={styles.anchors}><CircularAnchorRenderer svg={V2_SAMPLE_ANCHOR_SVGS.simple} category="Career" size="hero" /><CircularAnchorRenderer svg={V2_SAMPLE_ANCHOR_SVGS.medium} category="Creativity" size="medium" /><CircularAnchorRenderer svg={V2_SAMPLE_ANCHOR_SVGS.dense} category="Spirituality" size="thumbnail" /><CircularAnchorRenderer svg={V2_SAMPLE_ANCHOR_SVGS.dense} category="Focus" size="micro" /></View></V2Surface></V2Section>
    <V2Section><V2SectionHeader title="Thread Strength" supportingCopy="Evidence of movement; never a progression calculator." /><V2ContentStack><V2ThreadStrength value={22} category="Career" /><V2ThreadStrength value={50} category="Health" trend="flat" detail="steady this week" /><V2ThreadStrength value={68} delta={7} category="Career" trend="up" detail="from today’s Focus" /><V2ThreadStrength value={100} delta={0} category="Focus" trend="flat" /></V2ContentStack></V2Section>
    <V2Section><V2SectionHeader title="Loading and feedback" /><V2Surface><V2Skeleton height={24} width="55%" /><V2Skeleton height={16} width="90%" /><V2ActivityIndicator label="Loading your anchors" /><V2InlineError message="Couldn’t refresh your recent activity." onRetry={() => undefined} /><V2InlineError message="You’re offline. Your saved work is still available." offline /><V2EmptyState title="Nothing here yet" message="Future screens compose this state with an appropriate action." /></V2Surface></V2Section>
  </V2Screen>;
}
function Swatch({ name, color }: { name: string; color: string }) { return <View style={styles.swatch}><View style={[styles.color, { backgroundColor: color }]} /><Text style={styles.swatchName}>{name}</Text><Text style={styles.hex}>{color}</Text></View>; }
const styles = StyleSheet.create({ intro: { ...typography.bodyMD, color: colors.text.secondary, marginBottom: spacing[7] }, label: { ...typography.labelSM, color: colors.text.secondary, marginTop: spacing[3] }, swatches: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing[3], marginTop: spacing[2] }, swatch: { width: 72, gap: 3 }, color: { width: 32, height: 32, borderRadius: 8, borderWidth: 1, borderColor: colors.border.subtle }, swatchName: { ...typography.caption, color: colors.text.primary }, hex: { ...typography.caption, color: colors.text.secondary, fontSize: 9 }, display: { ...typography.displayMedium, color: colors.text.primary }, heading: { ...typography.headingLG, color: colors.text.primary }, body: { ...typography.bodyMD, color: colors.text.secondary }, caption: { ...typography.labelSM, color: colors.text.secondary }, numeric: { ...typography.numericLarge, color: colors.text.primary }, iconRow: { flexDirection: 'row', gap: spacing[3] }, badges: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing[2] }, rowTrailing: { ...typography.caption, color: colors.text.secondary }, anchors: { alignItems: 'center', gap: spacing[5] } });
